CREATE TYPE public.account_type AS ENUM ('Client', 'Admin');
ALTER TYPE public.account_type OWNER TO marsil1990;
-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);
CREATE TABLE IF NOT EXISTS public.services (
    serivce_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    service_name character varying NOT NULL,
    service_description character varying NOT NULL,
    service_price numeric(9, 0) NOT NULL,
    CONSTRAINT service_pkey PRIMARY KEY (serivce_id)
);